### ISSUE TITLE
Client is missing published tracks in certain conditions

### ISSUE THREAD

**Issue by davidzhao** [livekit/livekit-server#162]
**Describe the bug**
@bekriebel reported this in slack. When users are joining the room at the same time from across different regions (where latency is a bigger concern), sometimes clients are reporting `TrackSubscriptionFailure` events with the following logs:

```
could not find published track PA_8qxvzPbj3G3R TR_QKFBfQyMBW6Q
addSubscribedMediaTrack @ RemoteParticipant.js?f400:71
eval @ RemoteParticipant.js?f400:78
setTimeout (async)
addSubscribedMediaTrack @ RemoteParticipant.js?f400:77
eval @ RemoteParticipant.js?f400:78
setTimeout (async)
addSubscribedMediaTrack @ RemoteParticipant.js?f400:77
eval @ RemoteParticipant.js?f400:78
```

According to @bekriebel, he's able to produce this if the server instance is located in a node far way from him. (Frankfurt to Seattle)

**Server**
- Version: 0.13.6

**Client**
- SDK: JS
- Version: 0.13.6

**Comment by bekriebel** [comment]
Since the line numbers don't line up exactly, the code that is being referenced in the log above it here: https://github.com/livekit/client-sdk-js/blob/95db3244dc4dcdb3ef55a61ee4f35f6c5adf526b/src/room/participant/RemoteParticipant.ts

**Comment by bekriebel** [comment]
My reproduction scenario is as follows:

Server version 0.13.5 running on docker on fly.io. Three nodes in a cluster, (SEA, ORD, FRA).

JS Client version 0.13.6 running my FoundryVTT module: https://github.com/bekriebel/fvtt-module-avclient-livekit

All clients are Chrome on Windows 11. I'm opening one window in my main browser window and six additional windows in incognito tabs all from the same desktop located in SEA.

To more easily reproduce, I start a room on the FRA node, then switch all clients to use the ORD node for signaling. So each client has a low/moderate latency trip to the signaling node and a high latency trip to the SFU node. I have not yet tested which of these changes make the most difference, but I know I wasn't able to easily reproduce the error when I was doing everything through the SEA node in the cluster.

Each client connects about 1-2 seconds after the other (as quickly as I can switch between tabs and sign in to the next client). Because the latency is high to the SFU, multiple clients are negotiating their connections at the same time. I tend to start seeing the error somewhere between client 5 and 7. It's rare that the error doesn't happen with this configuration.

It does seem like the issue is more than just a delay. If I look at the RemoteParticipant object of the user with the missing track on the client that generated the error, the track will not be listed even after several minutes. If I go to other clients, some of them will have subscribed to the track successfully. However, it is common that if a track was missed by one client, it was missed by 2-3 others as well.

**Comment by bekriebel** [comment]
I upgraded my server to v0.13.6 and the issue is still reproducible.

**Comment by bekriebel** [comment]
I did some more testing with various scenarios. I can reproduce the issue in each of these setups, but there is a noticeable difference in how easy it is to cause it. For each test, I tried combinations of where the room (SFU) was hosted out of and where the signaling node was hosted. Each one is either close (low latency) or far (high latency).

Same node, close: low occurrence of issue
SFU close, signaling far: low/medium occurrence of issue
Same node, far: medium occurrence of issue
SFU far, signaling close: high occurrence of issue

In all cases, it seems to be the speed at which I connect the clients that also matters. If I connect them one after the other within a second or two of each other, I can reproduce the issue. If I pause between adding each client and give the connections a chance to settle, I haven't been able to reproduce the issue even in the worst case scenario (far SFU, close signaling server). If I use code to get all clients to reconnect at the exact same time, the issue is exacerbated even further.

**Comment by davidzhao** [comment]
thanks for providing so much detail on this. This is extremely helpful as we track this down.

**Comment by bekriebel** [comment]
I just realized something when trying to narrow this down further, the `RoomEvent.TrackPublished` event is fired for these missing tracks, but even in the Publication payload for the event, the tracks is missing track/audioTrack/videoTrack data. In this log, the video track came through properly but the audio track threw the TrackSubscriptionFailed error:

![image](https://user-images.githubusercontent.com/183779/139514577-e2f47218-eba8-478d-8b10-c6e7cbefd3d3.png)

**Comment by davidzhao** [comment]
> the `RoomEvent.TrackPublished` event is fired for these missing tracks

Really? this is for the same user that has seen the track subscription fail?

> the tracks is missing track/audioTrack/videoTrack data

this is expected. the publication need to show up first before they can be subscribed.

**Comment by bekriebel** [comment]
> > the `RoomEvent.TrackPublished` event is fired for these missing tracks
> 
> 
> 
> Really? this is for the same user that has seen the track subscription fail?
> 

Yeah, I thought that was really weird as well. The Screenshot is from a client that got the error and couldn't see the track.

**Comment by davidzhao** [comment]
I was able to get a consistent repro for this by following the steps that you had outlined (THANK YOU 🙏 )

The root cause was an improper work-around that we had put in place (for an old version of the client). When you get a chance, could you try to see if it resolves the issue for you?

I've pushed it to Docker as `0.13.7-SNAPSHOT`

**Comment by bekriebel** [comment]
Unfortunately, v0.13.7-SNAPSHOT does not seem to resolve this for me. I'm still seeing tracks published that are not being found when I go to subscribe.

![image](https://user-images.githubusercontent.com/183779/139556381-bdb65f65-831a-4ea1-99a4-8f0434ce2d73.png)
![image](https://user-images.githubusercontent.com/183779/139556389-f0bd1303-7c69-4e4f-850b-f4907873680a.png)

**Comment by davidzhao** [comment]
Hmm. perhaps it's not the same bug as I'd fixed. I was no longer able to reproduce this after the change.

Can you log to see if you are receiving TrackUnpublished messages for the same track? It might be a sequencing issue related to inconsistent delays.

**Comment by bekriebel** [comment]
It does not appear that I get `TrackUnpublished` events on the client that the error occurs on (the one that can't subscribe to the published track). If I watch on another client that was able to subscribe to the track, I see the `TrackUnpublished` event - but it does not seem to show up on the client that wasn't able to subscribe.

Also, with autoSubscribe enabled, it does seem like there are some instances where a `TrackPublished` event doesn't occur, but I still get the `TrackSubscriptionFailed` event for a track. So, I'm sometimes getting `TrackPublished` events and sometimes not for these "missing" tracks.

**Comment by davidzhao** [comment]
Kept trying different timing of things.. and was able to reproduce this again. It looks like we still have a race condition somewhere that sent the participant updates out of order. (so the last published track got "unpublished" eventually). Attached are logs illustrating this

1. participant update with state 1 (joining)
2. participant update with state 2 (active)
3. participant update with two tracks (both audio and video)
4. participant update with only a single track (video was not in this update)
5. we therefore thought it was an update, and sent a `TrackUnpublished` event for the video track
6. attempting to subscribe to the video track and failing.

<img width="1289" alt="Screen Shot 2021-10-30 at 4 47 55 PM" src="https://user-images.githubusercontent.com/320582/139561446-53042a01-850d-4cd5-9e73-3102b6420b2f.png">

**Comment by davidzhao** [comment]
@bekriebel I found it! pushed up the fix and updated docker build as well. (using the same tag so you'd have to force docker refresh)

This is a tricky one. Give it a shot.

**Comment by bekriebel** [comment]
I think we're getting somewhere! However, I seem to have triggered a new issue. When I did my "quickly connect one at a time" test, I didn't reproduce the error. However, when I issued a command that caused all 7 clients to disconnect and then reconnect at the same time, I seem to have completely brought down the SFU. The signaling side of the server is still responded (I can still get "new client WS connected" logs), but the server is completely unresponsive otherwise and it hangs the connections.

The only errors I see at the moment on the server side are: 
```json
{"level":"error","ts":1635643242.280819,"logger":"livekit","caller":"rtc/transport.go:224","msg":"could not create offer","error":"InvalidStateError: connection closed","stacktrace":"github.com/livekit/livekit-server/pkg/rtc.(*PCTransport).createAndSendOffer\n\t/workspace/pkg/rtc/transport.go:224\ngithub.com/livekit/livekit-server/pkg/rtc.(*PCTransport).CreateAndSendOffer\n\t/workspace/pkg/rtc/transport.go:178\ngithub.com/livekit/livekit-server/pkg/rtc.(*PCTransport).Negotiate.func1\n\t/workspace/pkg/rtc/transport.go:169"}
{"level":"error","ts":1635643242.281007,"logger":"livekit","caller":"rtc/transport.go:170","msg":"could not negotiate","error":"InvalidStateError: connection closed","stacktrace":"github.com/livekit/livekit-server/pkg/rtc.(*PCTransport).Negotiate.func1\n\t/workspace/pkg/rtc/transport.go:170"}
```

I only had time for a quick test, but I can try to gather more information and re-run the test again later.

**Comment by davidzhao** [comment]
The lock is likely causing some deadlocks. I'll look into it.

**Comment by davidzhao** [comment]
@bekriebel Take a look at the latest. I've done away with the additional lock to avoid deadlocking the signal node. Confirmed with my test harness that clients are receiving tracks properly.

**Comment by bekriebel** [comment]
@davidzhao I'm seeing definite improvement, but am still able to spawn the original error. If I log in manually one user at a time, it is not spawning the original error. However, if I have all clients reconnect at the same time, the original error occurs, and a lot more than previously. I now get several missed tracks on each of the clients.

On the SFU server side logs, I'm getting the following error even with just a couple of users connected:
```
pc ERROR: 2021/10/31 06:39:55 Incoming unhandled RTP ssrc(3759499990), OnTrack will not be fired. incoming SSRC failed Simulcast probing
```
I don't recall seeing this error previously, but it's possible that it is unrelated. Normally, this is only showing up occasionally when a user first joins, but in one instance after doing my stress reload, it started spamming the log continually until I signed the users out.

When the original TrackSubscriptionFailed log is spawned this time, the RemoteParticipant object does include the tracks.

![image](https://user-images.githubusercontent.com/183779/139571892-272e6bc2-3ea5-4ed6-a60c-e8cd30d1b502.png)

I know this is an odd scenario, but there are cases where the FoundryVTT site that I am integrating this into may cause all users to reload at the same time. Typically, differences in client machines will likely prevent them all from loading back in at the exact same time, though. Let me know if this is something I need to handle differently in my code instead.

As a side note, even when loading manually I'm also now seeing cases where one user is completely missing another when they first load in. This might be an edge case in my code, though. When I first sign in, I look for all existing participants and add them to a Map, and then subscribe to the participant joined event to add new users to the Map. I may just need to tweak how I handle this to make sure there's not a case where a user joins after I've scanned the participant list but before I've subscribed to the event. I'm only mentioning this in case it a sign of some other issue that may be causing the TrackSubscriptionFailed issues.

**Comment by davidzhao** [comment]
could you share the rough code you are using that triggers it?

is it still the same case where SFU is far but signaling node is closer?

I've tested having all 7 clients join and publish at the exact same time, and can no longer reproduce the original error.

The unhandled ssrc is a diff root cause, we'd have to dive into it separately.

**Comment by bekriebel** [comment]
The code I'm using is this: https://github.com/bekriebel/fvtt-module-avclient-livekit

The "all reloading at once" is caused when a setting changes which will cause an awaited `disconnect()` followed by `connect()` to be called on an instance of LiveKitAVClient.

Yes, I'm still testing on the split configuration. I'll try again on a singular server and a close server to see what the results are.

**Comment by davidzhao** [comment]
That's helpful, I'll see if I can get a similar repro. Though it sounds like we might be looking at a different issue.. since the tracks do appear to be there. Do you still see the error message like:
```
could not find published track PA_8qxvzPbj3G3R TR_QKFBfQyMBW6Q
```

> I now get several missed tracks on each of the clients.

Are the symptoms still similar when this happens? 

> As a side note, even when loading manually I'm also now seeing cases where one user is completely missing another when they first load in.

It'd be good to confirm by comparing against the internal state in `Room.participants`. If it's indeed missing participants entirely or if it's a missed callback.

**Comment by bekriebel** [comment]
> Do you still see the error message like:
> 
> ```
> could not find published track PA_8qxvzPbj3G3R TR_QKFBfQyMBW6Q
> ```

Yes, sorry - I just didn't include them in the snip because I assumed it was redundant.

> Are the symptoms still similar when this happens?

Yes, though it's also getting combined with the fact that users are missing at the same time.

> It'd be good to confirm by comparing against the internal state in `Room.participants`. If it's indeed missing participants entirely or if it's a missed callback.

When I check after everything has settled, `Room.participants` is populated properly. It seems to be a timing issue. With all of the users joining at once, I think by the time I'm subscribed to `RoomEvent.ParticipantConnected`, `Room.participants` has changed even if I attempt to subscribe to event before I scrape `RoomEvent.ParticipantConnected`.

To add to the "timing issue" concerns, I added some more logging. It turns out that at the time of `TrackPublished`, the track does not yet exist under the participant:
![image](https://user-images.githubusercontent.com/183779/139573706-7239a197-4d0b-42db-9c7d-43d0c44bfbed.png)

You can also see that in the `TrackPublished` event, the RemoteTrackPublication is actually missing the track data as well:
![image](https://user-images.githubusercontent.com/183779/139573789-3c7ac812-49e9-494f-9294-63d6d3769743.png)

If I look at the participant after everything has settled, the tracks are now listed:
![image](https://user-images.githubusercontent.com/183779/139573869-d02f786c-46a9-40e5-acb1-83b3de738219.png)

Is it possible to prevent the `TrackPublished` event from firing until the track data is fully populated?

**Comment by bekriebel** [comment]
> If I look at the participant after everything has settled, the tracks are now listed:

Scratch that. I looked closer, `RemoteParticipant.tracks` is populated with the `RemoteTrackPublication`s, but the publication itself is still missing the track even after everything has settled:

For example, in this one, the videoTrack is populated, but audioTrack is not:
![image](https://user-images.githubusercontent.com/183779/139573979-fd7470a5-269e-4be1-a5a4-9882040f2f4b.png)

**Comment by bekriebel** [comment]
I just tested the "reconnect all" test against closer node and could not reproduce either issue. This very well may be fine as-is. The other issue may be a manufactured edge case.

**Comment by bekriebel** [comment]
>It'd be good to confirm by comparing against the internal state in Room.participants. If it's indeed missing participants entirely or if it's a missed callback.

Last bit of debugging for this evening: I found that the "missing participants" issue seems to be getting caused by missing callback events. Again, with my "fast signaling, slow SFU" setup, if I keep one client connected & already subscribed to `RoomEvent.ParticipantConnected` and then issue a command to have 5 other clients connect at the same time, I only get a single `RoomEvent.ParticipantConnected` event.

This starts as soon as I have a total of 4 users (including the one I'm keeping connected). Consistently, if I connect 3 clients at the same time, I get only two `RoomEvent.ParticipantConnected` events. With 4 or more simultaneous connecting users, I start to only get a single `RoomEvent.ParticipantConnected` event.

This is still an edge case, but it is acting consistently for me with this setup.

**Comment by bekriebel** [comment]
I lied, one more test for the evening :-)

I reverted the servers back to v0.13.6 and tried `ParticipantConnected` tests again. On that version, I'm not able to reproduce the missing events issue. I still get the track issues, of course, but it seems the missing `ParticipantConnected` events issue was introduced with these changes.

**Comment by davidzhao** [comment]
> Last bit of debugging for this evening: I found that the "missing participants" issue seems to be getting caused by missing callback events.

Ah ok, this is helpful to know. So it sounds like you are missing `ParticipantConnected` events, but they actually appear in the internal state? Or do you find them to be missing from internal state as well?

> Is it possible to prevent the `TrackPublished` event from firing until the track data is fully populated?

No, this is by design. it always transitions from `published` (metadata) -> `subscribed` (actual track).

**Comment by davidzhao** [comment]
@bekriebel I've made another attempt at this, which doesn't change the mechanics of when the updates are delivered. When you get a chance to try, see if this resolves the missing `ParticipantConnected` events for you. 🙏

**Comment by bekriebel** [comment]
> @bekriebel I've made another attempt at this, which doesn't change the mechanics of when the updates are delivered. When you get a chance to try, see if this resolves the missing `ParticipantConnected` events for you. 🙏

I think you may have nailed it! I'm still running through all the tests I was doing, but so far this one is surviving the slow-sfu/fast-signaling tests.

I've every once in a while seeing a case where a single user's track isn't coming through. This seems to be an issue on the publishing end, though; when this happens, no user is seeing the track and even if I reconnect a client, I'm not seeing that published track associated with the participant.

I'm not seeing any errors on the offending user's side and they think the track is published. However, this is also much easier to deal with and still is only happening occasionally under extreme circumstances.

**Comment by bekriebel** [comment]
@davidzhao I've completed my tests. I can't find any scenario where I can cause the failed track error or the missing participant error 🥳 Nice work!

After stressing it some more, I've found that the "user missing a track for all clients" issue appears to be related to the server error `pc ERROR: 2021/10/31 21:26:22 Incoming unhandled RTP ssrc(3954959657), OnTrack will not be fired. incoming SSRC failed Simulcast probing`. When I notice a track is missing, it coincides with at error being spammed into the server log. I'm only ever able to trigger that one using my worst-case setup, and it doesn't happen every time. I can open a separate ticket for this, though - as you said, it's likely unrelated.

Thanks for all of your work on this! Please let me know if there are any other tests you'd like me to run.

**Comment by davidzhao** [comment]
woohoo! Thanks for confirming @bekriebel ! Super appreciate your help with getting to the bottom of this over the weekend.

Yeah, the unhandled ssrc is definitely another issue. we can file it as such and dive in later. That one worries me a bit less.
